# Setup
setup: moco
train_method: moco
version: moco


# Model
backbone: ResNet34
base_model: moco
feature_dim: 128
model_kwargs:
    input_size: [96, 96, 3]
    res_blocks: 30
    hidden_dim: 256
    out_dim: 128

# Dataset
train_db_name: stl-10
val_db_name: stl-10
num_classes: 10
split: train+unlabeled

# LossA
temperature: 0.1
criterion: clpcl
criterion_kwargs:
   temperature: 0.1 

# Hyperparameters
epochs: 500
optimizer: sgd
optimizer_kwargs:
   nesterov: False
   weight_decay: 0.0001 
   momentum: 0.9
   lr: 0.4
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1
batch_size: 512 
num_workers: 8

# Transformations
augmentation_strategy: scan 

augmentation_kwargs:
   crop_size: 96
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 96
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]